name: telotopic-signatures
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.0
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.1
  - scikit-learn=1.4.2
  - statsmodels=0.14.2
  - matplotlib=3.8.4
  - tqdm=4.66.4
  - beautifulsoup4=4.12.3
  - lxml=5.2.1
  - requests=2.31.0
  - ruamel.yaml=0.18.6
  - pip:
      - torch==2.3.0
      - transformers==4.41.2
      - sentence-transformers==2.7.0
      - tokenizers==0.15.2
      - spacy==3.7.4
      - spacy-transformers==1.3.5
      - nltk==3.8.1
      - emoji==2.12.1
      - ruptures==1.1.9
      - seaborn==0.13.2
      - jupyterlab==4.2.1
